const express = require('express');
const router = express.Router();
const passport = require('passport');
// pass passport variable and insert into configuration function 
const passportConf = require('../../config/passport');

const usersController = require('../../controllers/usersController');

// a shorthand middleware used to authenticate a given credential (JWT, fb creds)
const authenticate = (route, stratType) => {
	router.use(route, (req, res, next) => {
		// custom callback - needed to send error in JSON format
		passport.authenticate(stratType, (err, user, info) => {		
			if (err) {
				return res.status(401).json({
					message: "Authentication unsuccessful"
				});
			}

			// not sure if this is really needed 
			if (!user) {
				return res.status(401).json({
					message: "Authentication unsuccessful",
				});
			}

			// needed in order to turn session off (if not inserted, session is established)
			req.logIn(user, { session: false }, next);
		}) (req, res, next);
	});
};

// @route GET api/items
// @desc Get All Items
// @access Public

// @route POST api/items
// @desc Create A Post
// @access Public

// @route DELETE api/items/:id
// @desc Create A Item
// @access Public

// Chainable route handler, execute different functionalities depending on the type of request

/**
 * @api {get} /api/users/alluser Get all user's info from DB
 * @apiName GetAllUsers
 * @apiGroup Users
 *
 * @apiSuccess {User[]} Users Array of user's info
 *
 * @apiSuccessExample Successful Response:
 * HTTP/1.1 200 OK 
 * {
 *     "confirm": true,
 *	   "isAdmin": false,
 * 	   "_id": "5f644add72d3ff4a0413ff56",
 *	   "email": "itsmemario@gmail.com",
 *	   "username": "a",
 *	   "password": "$2a$10$vyPiyp4YrYxI20.wP4Suc.4dj7okRR5pM1g7s1j1UoTOJS09hWZ8G",
 *	   "date": "2020-09-18T05:51:25.921Z",
 *	   "__v": 0
 * },
 * {
 *	   "confirm": true,
 *	   "isAdmin": false,
 *	   "_id": "5f61fafd802dd1455cd488cc",
 *	   "email": "modofa1977@araniera.net",
 *	   "username": "a",
 *	   "password": "$2a$10$BUUI/8btB/pVQHPSZpey7O4QMdyQYl//M1nWKO6hMDXWTtu3KNmoO",
 * 	   "date": "2020-09-16T11:46:05.311Z",
 *	   "__v": 0
 * }
 */
router.route('/alluser')
    .get(usersController.getAllUser);

/**
 * @api {post} /register Register a user into our database
 * @apiName RegisterUser
 * @apiGroup Users
 *
 * @apiParam {String} email User's email, must be unique
 * @apiParam {String} username User's chosen username, not unique
 * @apiParam {String} password User's chosen password, not unique
 *
 * @apiParamExample Example Body: 
 * {
 *     "email": "bobdillon@gmail.com",
 *     "username": "Bobby123",
 *	   "password": "Bobby123"
 * }
 *
 * @apiSuccess {String} status Registration results
 *
 * @apiSuccessExample Sucessful Response:
 * HTTP/1.1 201 OK
 * {
 *     "status": "Thank you for registering - Please confirm your email address."
 * }
 *
 * @apiError (200) EmailAlreadyRegistered Email inputted is already registered in database.
 * 
 * @apiErrorExample Error-Response:
 * HTTP/1.1 200 OK
 * {
 *     "status": "Email is already registered"	
 * }
 */
router.route('/register')
    .post(usersController.checkBody, usersController.registerNewUser);


router.route('/confirmation/:userId')
    .get(usersController.userEmailConfirmation);

/**
 * @api {post} /login Login user into our website
 * @apiName LoginUser
 * @apiGroup Users
 *
 * @apiParam {String} email User's email
 * @apiParam {String} password User's password
 *
 * @apiParamExample Example Body:
 * {
 *     "email":	"modofa1977@araniera.net",
 *	   "password": "a"
 * }
 *
 * @apiSuccess {String} message login successful message
 * @apiSuccess {String} token Access token generated when user successfully logs in
 * 
 * @apiSuccessExample Successful Response:
 * HTTP/1.1 200
 * {
 *     "message": "Login sucessful",
 *     "token": "Bearer foawheof8f89k23nkjy87yfiuawfkhfaiuwhui"
 * }
 * 
 * @apiError IncorrectUserDetails Email already exist or password is wrong
 * 
 * @apiErrorExample Error-Response: 
 * HTTP/1.1 401 Unauthorized
 * {
 *     "message": "Email or Password is incorrect."
 * }
 */
router.route('/login')
	.post(usersController.loginUser);

/**
 * @api {post} /oauth/facebook User uses facebook to login our website
 * @apiName LoginFacebookUser
 * @apiGroup Users
 *
 * @apiParam {String} access_token access token generated by Facebook when user signs through FB
 *
 * @apiParamExample Example Body:
 * {
 *     "access_token":	"EAALIqkOxw2EBAGCjqTUx6NiSzC2Ofku8qwqxxauWJzhNclMuqTr780xWGqWSPiVXSzCRMl"
 * }
 *
 * @apiSuccess {String} message login successful message
 * @apiSuccess {String} token Access token generated when user successfully logs in
 * 
 * @apiSuccessExample Successful Response:
 * HTTP/1.1 200
 * {
 *     "message": "Authentication Sucessful",
 *     "token": "Bearer foawheof8f89k23nkjy87yfiuawfkhfaiuwhui"
 * }
 * 
 * @apiError IncorrectFacebookCredentials Wrong access token is provided
 * 
 * @apiErrorExample Error-Response: 
 * HTTP/1.1 401 Unauthorized
 * {
 *     "message": "Authentication unsuccessful"
 * }
 */
router.route('/oauth/facebook', authenticate('/oauth/facebook', 'facebookToken'))
	.post(usersController.oAuth);

/**
 * @api {post} /oauth/google User uses google to login our website
 * @apiName LoginGoogleUser
 * @apiGroup Users
 *
 * @apiParam {String} access_token access token generated by Google when user signs through Google
 *
 * @apiParamExample Example Body:
 * {
 *     "access_token":	"EAljafjaojoiaewfhiafhfajKLFJhhaflj80xWGqWSPiVXSzCRMl"
 * }
 *
 * @apiSuccess {String} message login successful message
 * @apiSuccess {String} token Access token generated when user successfully logs in
 * 
 * @apiSuccessExample Successful Response:
 * HTTP/1.1 200
 * {
 *     "message": "Authentication Sucessful",
 *     "token": "Bearer joiawjioj98uq4q98t98thiajkgj"
 * }
 * 
 * @apiError IncorrectGoogleCredentials Wrong access token is provided
 * 
 * @apiErrorExample Error-Response: 
 * HTTP/1.1 401 Unauthorized
 * {
 *     "message": "Authentication unsuccessful"
 * }
 */
router.route('/oauth/google')
	.post(passport.authenticate('googleToken', { session: false }));

// THIS IS FOR TESTING (TO MAKE SURE THAT TOKENS ARE VALIDATED)
// authentication middleware passed here to make sure if token is valid
router.route('/test', authenticate('/test', 'jwt'))
	.get(usersController.testUser);

module.exports = router;